#!/usr/bin/env python
"""Regenerate the colored terminal SVGs embedded in the docs.

Every ``console`` block that shows real tool output — the pytest memory table,
``benchmem compare --diff``, the ``benchmem flamegraph`` summary — is captured
here as an SVG so the docs show the *actual* ANSI colors, not a monochrome code
fence. The SVGs are committed under ``docs/assets/`` and regenerated by running:

    python scripts/gen_doc_assets.py

The story is a realistic "use a lighter row type" fix: a list-of-dicts original
(before) vs a list-of-tuples candidate (after). The table shows the after run,
``compare --diff`` shows the memory dropping, and the summary localises the
allocation to the offending comprehension.
"""

from __future__ import annotations

import io
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

from rich.console import Console
from rich.text import Text

REPO = Path(__file__).resolve().parent.parent
ASSETS = REPO / "docs" / "assets"

# rich exports its SVGs with only a viewBox (no width/height), so a browser
# would rescale each to whatever CSS width it's given — making a narrow table's
# text larger than a wide one's. We instead bake an explicit width/height at one
# fixed SCALE into every asset, so all three render their monospace text at the
# same physical size (roughly the page's code font) regardless of column count.
SCALE = 0.62

# A short, fixed work dir so memray records tidy paths (report.py:2) in the
# summary instead of a long, machine-specific temp path.
WORK = Path("/tmp/benchmem-doc-assets")

# Non-SGR CSI escapes (cursor moves, line erases, hide/show cursor) that
# memray's progress spinner emits. SGR color codes end in 'm' and are kept.
_CURSOR_CSI = re.compile(r"\x1b\[[0-9;?]*[A-HJKlh]")
_SPINNER_TEXT = re.compile(r"Calculating high watermark|Processing allocation records")

# The intro table uses the same test_sort example the Home/Quickstart pages
# already show, so the colored capture drops in without a naming mismatch.
SORT_SUITE = """
import pytest

@pytest.mark.parametrize("n", [10_000, 100_000, 1_000_000])
def test_sort(benchmark, n):
    benchmark(sorted, list(range(n, 0, -1)))
"""

# The before/after story: a list-of-dicts original slimmed to list-of-tuples.
ROWS_SUITE = """
import pytest

@pytest.mark.parametrize("n", [10_000, 100_000, 500_000])
def test_build_rows(benchmark, n):
    benchmark(lambda: {row})
"""
TUPLES_ROW = "[(i, i * i) for i in range(n)]"  # after — the lighter fix
DICTS_ROW = '[{"x": i, "sq": i * i} for i in range(n)]'  # before — the heavy original

# Small, deep-stacked workload for the flamegraph summary: named helpers give
# the summary real frames (build_report -> _rows -> listcomp) to attribute to.
PROFILE_SUITE = """
import pytest

def _rows(n):
    return [{"id": i, "payload": "x" * 64} for i in range(n)]

def build_report(n):
    rows = _rows(n)
    return {"rows": rows, "index": {r["id"]: r for r in rows}}

def test_build_report(benchmark):
    benchmark(lambda: build_report(20_000))
"""

BENCH = [
    "--benchmark-only",
    "--benchmark-memory",
    "-q",
    "-p",
    "no:cacheprovider",
    # Keep asset generation fast — the numbers only need to look plausible.
    "--benchmark-warmup=off",
    "--benchmark-min-rounds=3",
    "--benchmark-max-time=0.1",
]


def run(cmd: list[str], cwd: Path, cols: int, timeout: int = 180) -> str:
    """Run a command with color forced on at a fixed width; return its stdout."""
    env = {**os.environ, "FORCE_COLOR": "1", "COLUMNS": str(cols), "LINES": "40"}
    proc = subprocess.run(cmd, cwd=cwd, env=env, capture_output=True, text=True, timeout=timeout)
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout + proc.stderr)
        proc.check_returncode()
    return proc.stdout


def strip_progress(ansi: str) -> str:
    """Drop memray's transient progress-spinner lines (cursor controls + text)."""
    out = []
    for line in _CURSOR_CSI.sub("", ansi).split("\n"):
        if _SPINNER_TEXT.search(line):
            continue
        out.append(line)
    return "\n".join(out)


def sanitize_paths(ansi: str) -> str:
    """Strip local filesystem paths so committed assets aren't machine-specific."""
    return ansi.replace(str(REPO), "…/pytest_benchmem").replace(os.path.expanduser("~"), "~")


def to_svg(ansi: str, out: Path, title: str) -> None:
    """Render ANSI text to a terminal-window SVG, auto-fitting the width.

    Width fits the content but never falls below the title length (plus room for
    the window's traffic-light dots), so a short table can't let the centered
    title collide with the dots.
    """
    ansi = ansi.strip("\n")
    lines = ansi.split("\n")
    content = max((Text.from_ansi(ln).cell_len for ln in lines), default=80)
    width = min(max(content + 1, len(title) + 8), 140)
    console = Console(record=True, width=width, file=io.StringIO(), force_terminal=True)
    console.print(Text.from_ansi(ansi))
    svg = _scale_svg(console.export_svg(title=title))
    out.write_text(svg)
    print(f"  wrote {out.relative_to(REPO)}  ({width} cols)")


def _scale_svg(svg: str) -> str:
    """Give the SVG an explicit width/height at the shared SCALE.

    Without this the SVG carries only a viewBox, so the browser sizes it to the
    CSS width and the rendered text size varies from asset to asset. Pinning
    width/height to viewBox * SCALE makes the text size uniform everywhere.
    """
    m = re.search(r'viewBox="0 0 ([\d.]+) ([\d.]+)"', svg)
    if not m:
        return svg
    w, h = float(m.group(1)) * SCALE, float(m.group(2)) * SCALE
    return svg.replace("<svg ", f'<svg width="{w:.0f}" height="{h:.0f}" ', 1)


def main() -> None:
    """Run the benchmark suites and write every doc-asset SVG under docs/assets/."""
    ASSETS.mkdir(parents=True, exist_ok=True)
    if WORK.exists():
        shutil.rmtree(WORK)
    WORK.mkdir(parents=True)
    py = sys.executable
    rows = WORK / "test_rows.py"
    after, before = WORK / "after.json", WORK / "before.json"

    # 1. The standalone memory table — the test_sort intro example.
    print("run: test_sort intro table…")
    sort_suite = WORK / "test_sortbench.py"
    sort_suite.write_text(SORT_SUITE)
    table = run(
        [py, "-m", "pytest", str(sort_suite), *BENCH, "--benchmark-columns=min"],
        WORK,
        cols=110,
    )
    to_svg(
        table, ASSETS / "benchmark-memory-table.svg", "pytest --benchmark-only --benchmark-memory"
    )

    # 2. The after run (lighter tuples) for the compare story.
    print("run: after (list of tuples)…")
    rows.write_text(ROWS_SUITE.format(row=TUPLES_ROW))
    run(
        [
            py,
            "-m",
            "pytest",
            str(rows),
            *BENCH,
            "--benchmark-columns=min",
            f"--benchmark-json={after}",
        ],
        WORK,
        cols=118,
    )

    # 3. The before run (heavier dicts).
    print("run: before (list of dicts)…")
    rows.write_text(ROWS_SUITE.format(row=DICTS_ROW))
    run(
        [
            py,
            "-m",
            "pytest",
            str(rows),
            *BENCH,
            "--benchmark-columns=min",
            f"--benchmark-json={before}",
        ],
        WORK,
        cols=118,
    )

    # 4. compare --diff: before -> after, so peak drops (green).
    print("benchmem compare --diff…")
    diff = run(
        [
            "benchmem",
            "compare",
            str(before),
            str(after),
            "--columns",
            "peak",
            "--diff",
            "--sort",
            "value",
        ],
        WORK,
        cols=84,
    )
    to_svg(diff, ASSETS / "compare-diff.svg", "benchmem compare --columns peak --diff")

    # 5. flamegraph summary: localise the allocation to the offending frame.
    print("profiled run + benchmem flamegraph --report summary…")
    psuite = WORK / "report.py"
    profiles = WORK / "profiles"
    psuite.write_text(PROFILE_SUITE)
    run(
        [py, "-m", "pytest", str(psuite), *BENCH, "--benchmark-memory-profile", str(profiles)],
        WORK,
        cols=100,
    )
    summary = run(
        ["benchmem", "flamegraph", str(profiles), "--worst", "peak", "--report", "summary"],
        WORK,
        cols=100,
        timeout=120,
    )
    to_svg(
        sanitize_paths(strip_progress(summary)),
        ASSETS / "flamegraph-summary.svg",
        "benchmem flamegraph profiles/ --worst peak --report summary",
    )

    shutil.rmtree(WORK, ignore_errors=True)
    print("done.")


if __name__ == "__main__":
    main()
