#!/usr/bin/env python
"""Regenerate the colored terminal SVGs embedded in the docs.

Every ``console`` block that shows real tool output — the pytest memory table,
``benchmem compare --diff``, the ``benchmem flamegraph`` summary — is captured
here as an SVG so the docs show the *actual* ANSI colors, not a monochrome code
fence. The SVGs are committed under ``docs/assets/`` and regenerated by running:

    python scripts/gen_doc_assets.py

The story is a real, tested optimization from ``examples/pairwise.py``: a naive
pairwise-distance function that materialises an ``(n, n, d)`` broadcast temporary
(before) vs the Gram-matrix identity that doesn't (after). ``compare --diff``
shows peak dropping ~82%, and the summary localises that peak to the broadcast
temporary. The intro table is a separate, simpler ``test_sort`` capture.
"""

from __future__ import annotations

import io
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

from rich.console import Console
from rich.text import Text

REPO = Path(__file__).resolve().parent.parent
ASSETS = REPO / "docs" / "assets"

# rich exports its SVGs with only a viewBox (no width/height), so a browser
# would rescale each to whatever CSS width it's given — making a narrow table's
# text larger than a wide one's. We instead bake an explicit width/height at one
# fixed SCALE into every asset, so all three render their monospace text at the
# same physical size (roughly the page's code font) regardless of column count.
SCALE = 0.62

# A short, fixed work dir so memray records tidy paths (report.py:2) in the
# summary instead of a long, machine-specific temp path.
WORK = Path("/tmp/benchmem-doc-assets")

# Non-SGR CSI escapes (cursor moves, line erases, hide/show cursor) that
# memray's progress spinner emits. SGR color codes end in 'm' and are kept.
_CURSOR_CSI = re.compile(r"\x1b\[[0-9;?]*[A-HJKlh]")
_SPINNER_TEXT = re.compile(r"Calculating high watermark|Processing allocation records")
# A memray-truncated absolute path: starts with / or ~, ends with the "…" glyph,
# no spaces or table borders in between. (Truncated numbers have no leading /.)
_LEAKED_PATH = re.compile(r"[~/][^\s│┃]*…")

# The intro table uses the same test_sort example the Home/Quickstart pages
# already show, so the colored capture drops in without a naming mismatch.
SORT_SUITE = """
import pytest

@pytest.mark.parametrize("n", [10_000, 100_000, 1_000_000])
def test_sort(benchmark, n):
    benchmark(sorted, list(range(n, 0, -1)))
"""

# The before/after story: the naive pairwise-distance implementation (which
# materialises an (n, n, d) temporary) slimmed to the Gram-matrix identity.
# Both runs share the test id so `compare` pairs them; only the imported
# function differs. See examples/pairwise.py (tested in tests/test_examples.py).
DIST_SUITE = """
import numpy as np
import pytest
from examples.pairwise import {fn} as impl

@pytest.mark.parametrize("n", [200, 400, 800])
def test_pairwise_dists(benchmark, n):
    x = np.random.default_rng(0).standard_normal((n, 16))
    benchmark(lambda: impl(x))
"""
NAIVE_FN = "pairwise_sq_dists_naive"  # before — the (n, n, d) memory hog
FIXED_FN = "pairwise_sq_dists"  # after — the O(n²) identity

# Single-run profile for the flamegraph summary: the naive implementation at one
# size, so the summary attributes peak to the broadcast temporary it allocates.
# Imports a copy of pairwise.py placed in WORK, so the profiled frame shows a
# tidy /tmp path instead of a long, machine-specific one.
PROFILE_SUITE = """
import numpy as np
import pytest
from pairwise import pairwise_sq_dists_naive

def test_pairwise_dists(benchmark):
    x = np.random.default_rng(0).standard_normal((800, 16))
    benchmark(lambda: pairwise_sq_dists_naive(x))
"""

BENCH = [
    "--benchmark-only",
    "--benchmark-memory",
    "-q",
    "-p",
    "no:cacheprovider",
    # Keep asset generation fast — the numbers only need to look plausible.
    "--benchmark-warmup=off",
    "--benchmark-min-rounds=3",
    "--benchmark-max-time=0.1",
]


def run(cmd: list[str], cwd: Path, cols: int, timeout: int = 180) -> str:
    """Run a command with color forced on at a fixed width; return its stdout."""
    # Put the repo root on the path so the benchmark suites can import examples/.
    pypath = os.pathsep.join(filter(None, [str(REPO), os.environ.get("PYTHONPATH", "")]))
    env = {
        **os.environ,
        "FORCE_COLOR": "1",
        "COLUMNS": str(cols),
        "LINES": "40",
        "PYTHONPATH": pypath,
    }
    proc = subprocess.run(cmd, cwd=cwd, env=env, capture_output=True, text=True, timeout=timeout)
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout + proc.stderr)
        proc.check_returncode()
    return proc.stdout


def strip_progress(ansi: str) -> str:
    """Drop memray's transient progress-spinner lines (cursor controls + text)."""
    out = []
    for line in _CURSOR_CSI.sub("", ansi).split("\n"):
        if _SPINNER_TEXT.search(line):
            continue
        out.append(line)
    return "\n".join(out)


def sanitize_paths(ansi: str) -> str:
    """Collapse leaked local paths so committed assets aren't machine-specific.

    The example lives under WORK (a short, fixed ``/tmp`` dir) so its path shows
    in full. Every other path in the report — the tool's own frames, numpy
    internals — is a long absolute path memray truncates to end with ``…``;
    collapse those to a bare ellipsis rather than bake in a home/worktree path.
    """
    return _LEAKED_PATH.sub("…", ansi)


def to_svg(ansi: str, out: Path, title: str) -> None:
    """Render ANSI text to a terminal-window SVG, auto-fitting the width.

    Width fits the content but never falls below the title length (plus room for
    the window's traffic-light dots), so a short table can't let the centered
    title collide with the dots.
    """
    ansi = ansi.strip("\n")
    lines = ansi.split("\n")
    content = max((Text.from_ansi(ln).cell_len for ln in lines), default=80)
    width = min(max(content + 1, len(title) + 8), 140)
    console = Console(record=True, width=width, file=io.StringIO(), force_terminal=True)
    console.print(Text.from_ansi(ansi))
    svg = _scale_svg(console.export_svg(title=title))
    out.write_text(svg)
    print(f"  wrote {out.relative_to(REPO)}  ({width} cols)")


def _scale_svg(svg: str) -> str:
    """Give the SVG an explicit width/height at the shared SCALE.

    Without this the SVG carries only a viewBox, so the browser sizes it to the
    CSS width and the rendered text size varies from asset to asset. Pinning
    width/height to viewBox * SCALE makes the text size uniform everywhere.
    """
    m = re.search(r'viewBox="0 0 ([\d.]+) ([\d.]+)"', svg)
    if not m:
        return svg
    w, h = float(m.group(1)) * SCALE, float(m.group(2)) * SCALE
    return svg.replace("<svg ", f'<svg width="{w:.0f}" height="{h:.0f}" ', 1)


def main() -> None:
    """Run the benchmark suites and write every doc-asset SVG under docs/assets/."""
    ASSETS.mkdir(parents=True, exist_ok=True)
    if WORK.exists():
        shutil.rmtree(WORK)
    WORK.mkdir(parents=True)
    py = sys.executable
    dist = WORK / "test_dists.py"
    after, before = WORK / "after.json", WORK / "before.json"

    # 1. The standalone memory table — the test_sort intro example.
    print("run: test_sort intro table…")
    sort_suite = WORK / "test_sortbench.py"
    sort_suite.write_text(SORT_SUITE)
    table = run(
        [py, "-m", "pytest", str(sort_suite), *BENCH, "--benchmark-columns=min"],
        WORK,
        cols=110,
    )
    to_svg(
        table, ASSETS / "benchmark-memory-table.svg", "pytest --benchmark-only --benchmark-memory"
    )

    # 2. The after run (optimised identity) for the compare story.
    print("run: after (Gram-matrix identity)…")
    dist.write_text(DIST_SUITE.format(fn=FIXED_FN))
    run(
        [
            py,
            "-m",
            "pytest",
            str(dist),
            *BENCH,
            "--benchmark-columns=min",
            f"--benchmark-json={after}",
        ],
        WORK,
        cols=118,
    )

    # 3. The before run (naive broadcast).
    print("run: before (naive broadcast)…")
    dist.write_text(DIST_SUITE.format(fn=NAIVE_FN))
    run(
        [
            py,
            "-m",
            "pytest",
            str(dist),
            *BENCH,
            "--benchmark-columns=min",
            f"--benchmark-json={before}",
        ],
        WORK,
        cols=118,
    )

    # 4. compare --diff: before -> after, so peak drops (green).
    print("benchmem compare --diff…")
    diff = run(
        [
            "benchmem",
            "compare",
            str(before),
            str(after),
            "--columns",
            "peak",
            "--diff",
            "--sort",
            "value",
        ],
        WORK,
        cols=84,
    )
    to_svg(diff, ASSETS / "compare-diff.svg", "benchmem compare --columns peak --diff")

    # 5. flamegraph summary: localise the allocation to the offending frame.
    print("profiled run + benchmem flamegraph --report summary…")
    psuite = WORK / "bench_pairwise.py"
    profiles = WORK / "profiles"
    shutil.copy(REPO / "examples" / "pairwise.py", WORK / "pairwise.py")
    psuite.write_text(PROFILE_SUITE)
    run(
        [py, "-m", "pytest", str(psuite), *BENCH, "--benchmark-memory-profile", str(profiles)],
        WORK,
        cols=100,
    )
    summary = run(
        ["benchmem", "flamegraph", str(profiles), "--worst", "peak", "--report", "summary"],
        WORK,
        cols=100,
        timeout=120,
    )
    to_svg(
        sanitize_paths(strip_progress(summary)),
        ASSETS / "flamegraph-summary.svg",
        "benchmem flamegraph profiles/ --worst peak --report summary",
    )

    shutil.rmtree(WORK, ignore_errors=True)
    print("done.")


if __name__ == "__main__":
    main()
